#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1
PROG=/usr/bin/discord-resolver.sh

start_service() {
    logger "Starting discord-resolver"

    procd_open_instance
    procd_set_param command "$PROG" start $@
    procd_set_param respawn
    procd_close_instance
}

stop_service() {
    killall -q discord-resolver.sh
    logger "Stopped discord-resolver"
}

status() {
    if pidof discord-resolver.sh >/dev/null; then
        echo "Running"
        return 0
    else
        echo "Stopped"
        return 1
    fi
}
